### ISSUE TITLE
Performance: splice or null?

### ISSUE THREAD

**Issue by wardbell** [jdanyow/aurelia-breeze#10]
Hi Jeremy

I looked again at the code. I think it is much better. Again, I'm only reading it but it seems much improved to me.

I had a lingering question about whether it is "better" to modify the subscription callback arrays during unsubscribe or to set the array slot with null and then fill the null holes with the next subscription.

I wrote [a gist](https://gist.github.com/wardbell/d843cd7863f70a2a5b8b) to test both ways of doing it, jacked up the iteration counts, and looked at it in the chrome profiler.

If I'm doing it right, the set-and-fill-with-nulls approach is faster. Not crazy faster but faster. For example, in one set of runs (alternating slice and null version trials three times), the slice approach took 6 seconds while the null approach took 5 seconds.

Each trial:
- adds a subscription to a property named "first"
- does the following 1,000,000 times:
  - adds a subscription for property X
  - simulates raising a property changed event (by calling  `observer.subscription`).
  - removes that property subscription
- removes the "first" subscription so that the observer's subscribe event simulation is cleared

Is that significant? Probably not in the grand scheme of things. But Jay did it this way in breeze so maybe we should do it here too.   Your call.

btw, I followed the profiling instructions [here](https://developer.chrome.com/devtools/docs/cpu-profiling).

**Comment by jdanyow** [comment]
As part of the aurelia benchmarking work we ended up removing all object/array allocations and closures that we could in favor of first/second/third/rest properties and "callables".  This work was applied to the aurelia-breeze plugin as well.  There's no longer a callbacks/subscriptions array on the observer.
