### ISSUE TITLE
Tweaks to BreezeObservationAdapter methods

### ISSUE THREAD

**Issue by wardbell** [jdanyow/aurelia-breeze#11]
While investigating splice-vs-null setting (see [this issue](https://github.com/jdanyow/aurelia-breeze/issues/10)), I tripped over a few adjustments you might want to make.

All of them can be found in [this gist](https://gist.github.com/wardbell/d843cd7863f70a2a5b8b).
## subscribe

Instead of repeatedly executing `this.callbacks[propertyName]`, I would capture that array. Your splicing version would look like this:

```
function subscribe(propertyName, callback){
    var callbacks = this.callbacks[propertyName];
    if (!callbacks) {
      this.callbacks[propertyName] = [callback];
    } else if (callbacks.indexOf(callback) === -1) {
      callbacks.push(callback);
    } else {
      return; // already registered; ignore.
    }

    if (this.callbackCount === 0) {
      this.subscription = this.obj.entityAspect.propertyChanged.subscribe(this.handleChanges.bind(this));
    }

    this.callbackCount += 1;

    return this.unsubscribe.bind(this, propertyName, callback);
}
```

> I think you are correct to ignore an attempt to re-register the same callback function rather than throw. OTOH, I prefer moving the `elses` around because I find it easier to read a positive (`=== -1`) rather than a negative (`!=== -1`). Don't you?
## unsubscribe

Instead of calculating the index of the callback twice, I would call it once.

I guard against a failure to find the callback for a particular property, whether that's because the callback isn't registered or because there aren't any subscriptions for that property. Both cases I treat as "no-ops".

I also think it is safer (from a memory leak perspective) to zap the `this.callbacks` when there are no more subscriptions.

My revised version looks like this:

```
function unsubscribe(propertyName, callback) {
    var callbacks = this.callbacks[propertyName];
    if (!callbacks) { return; } // no subscriptions for this property; ignore.
    var index = callbacks.indexOf(callback);
    if (index === -1) { return; } // this callback was not found; ignore.
    callbacks.splice(index, 1);
    this.callbackCount -= 1;
    if (this.callbackCount === 0) {
      this.obj.entityAspect.propertyChanged.unsubscribe(this.subscription);
      this.callbacks={};
    }
}
```

> Per Crockford, I'm using `this.callbackCount += 1` and `this.callbackCount -= 1` instead of `this.callbackCount++` and `this.callbackCount--`.  That change is _really_ picky.

**Comment by jdanyow** [comment]
Good stuff- just realized- if we don't throw I think we'll need to return the unsubscribe function like this: 

``` javascript
function subscribe(propertyName, callback){
  var callbacks = this.callbacks[propertyName];
  if (!callbacks) {
    this.callbacks[propertyName] = [callback];
  } else if (callbacks.indexOf(callback) === -1) {
    callbacks.push(callback);
  } else {
    return this.unsubscribe.bind(this, propertyName, callback);  // <--------
  }

  if (this.callbackCount === 0) {
    this.subscription = this.obj.entityAspect.propertyChanged.subscribe(this.handleChanges.bind(this));
  }

  this.callbackCount += 1;

  return this.unsubscribe.bind(this, propertyName, callback);
}
```

Still conflicted on this...  throwing might help people find issues in their code or in the aurelia framework.  Not throwing is probably harmless though... going to run this by some more people

**Comment by wardbell** [comment]
Hmm. Ok. I see you have to return an unsubscribe fn. And we can't be sure WHICH returned fn will be called first.

But does it really matter whether we unsubscribe for the first or second one? I guess your approach is as good as any.

I would likely do this:

```
function subscribe(propertyName, callback){
  var callbacks = this.callbacks[propertyName];
  var unsub = this.unsubscribe.bind(this, propertyName, callback);  // <--------
  if (!callbacks) {
    this.callbacks[propertyName] = [callback];
  } else if (callbacks.indexOf(callback) === -1) {
    callbacks.push(callback);
  } else {
    return unsub ;
  }

  if (this.callbackCount === 0) {
    this.subscription = this.obj.entityAspect.propertyChanged.subscribe(this.handleChanges.bind(this));
  }

  this.callbackCount += 1;

  return unsub;
}
```

**Comment by jdanyow** [comment]
Went back and looked at the observers this stuff was originally modeled after in the Aurelia codebase:
- [OoObserver.subscribe](https://github.com/aurelia/binding/blob/master/src/property-observation.js#L89)
- [SetterObserver.subscribe](https://github.com/aurelia/binding/blob/master/src/property-observation.js#L52)
- [ValueAttributeObserver.subscribe](https://github.com/aurelia/binding/blob/master/src/element-observation.js#L105)

These don't care about subscribing multiple times with the same callback, the end result is the callback is invoked twice.  They also preserve the order of the callbacks.

The changes I've made to check for an existing subscription diverge from the "behavior contract".  Likewise, switching from splice to null-setting on unsubscribe will diverge further (in terms of callback invocation order).  I'm not sure if any of this matters but it would be good if the behavior was consistent across the aurelia and aurelia-breeze.  Maybe we make the changes here AND in aurelia, or maybe we refactor aurelia-breeze a bit to be consistent with aurelia's behavior.

@EisenbergEffect - any thoughts on this?

**Comment by wardbell** [comment]
First, I agree that consistency across Aurelia trumps all. Everything else here is commentary.

It is true that the null setting approach will change callback order. I never though about that in breeze where we use this technique for registering entities in cache (not events); for example, you cannot count on getting todos out of cache in the same order that you added them.

In principle, an event subscriber is not supposed to care nor should be able to count on callback order. That indifference is intrinsic to the semantics of events and asynchrony generally (although order may be a guarantee for (some) streams).

But in practice we know that the dev often cheats ... as when counting on the call order of tests (and thus leveraging cross-test pollution).

Personally, I think cheating should be discouraged, particularly if it interferes with perf optimization. But I'd  understand if you all felt otherwise.

Calling the same callback twice makes no sense to me.

.Net events work that way too. It is a constant PITA. Easy to accidentally double subscribe and then not know how many times to unsubscribe. You often followed the idiom of unsubscribing defensively before subscribing.

I know it is harmless to unsubscribe the same callback multiple times.

If you want this behavior we have to stop checking if the sub is in the array. That would make subscribing a little faster. This particular point has no material effect on the null-v-splice issue.

Sent from my Windows Phone

**Comment by EisenbergEffect** [comment]
Ultimately, we are not going to be able to guarantee order. If we do, we have to give up a lot of performance. Also for perforamance, we will need to get rid of the arrays. That's also a memory problem. @jdanyow Look at the latest implementation of MetadataStore inside the metadata repo. You will see a pattern that we will want to switch to for _all_ subscriptions. The pattern uses a combination of fields and an array for overflow. It is _much_ faster and better on memory and GC. This is on the list of optimizations to be made throughout the entire binding system once we get the benchmarking tool ready to go. There are a number of other optimizations like this related to subscribers as well. Ultimately, the bulk of all binding operations should never create or touch an array, nor create a closure. This is huge for performance. I would like to get this work done in the core as soon as we can benchmark it. Then after that we can come back to the breeze integration and improve that. It will be needed since there will be some breaking changes at this level.

**Comment by wardbell** [comment]
Oooo. Jeremy ... when you figure this out, do let me know. Maybe we can transport that goodness to breeze core where it makes sense.

**Comment by EisenbergEffect** [comment]
@wardbell I'd be happy to help you guys make some improvements. You may not be able to leverage all of them because some will make the api a little more clunky. We can do that in our binding engine because it's parts that aren't normally directly interacted with by developers. You would need to decided for Breeze whether the same changes made sense.

**Comment by jdanyow** [comment]
wow- neat technique:  https://github.com/aurelia/metadata/blob/master/src/metadata.js#L28-L58

was also wondering if a linked list structure would be an efficient way of handling this

**Comment by EisenbergEffect** [comment]
@jdanyow That's another possibility. If you want to do some jsperf between this and a linked list structure, that would be cool. One of the things about this approach is that it optimizes around the idea that there usually won't be more than 3 "items in the list". So, fields are used for that, but it doesn't prevent more by using the array as a fallback. But the common scenario, is optimized. My gut is that this is faster then linked lists, but I would love to confirm. I did do tests against arrays for x number of operations and this was clearly better.

**Comment by wardbell** [comment]
That makes great sense when you expect very few of something most of the time. It also uses null setting ... in the first three fixed slots.

Not such a good fit for an entity cache :-)  I think we're driven to arrays there in which case null setting is a demonstrable improvement over splicing.

But we can look elsewhere in Breeze for short, frequently accessed collections where this makes a ton of sense.

 I wonder if this can be generalized into some kind of ShortList abstraction.

**Comment by EisenbergEffect** [comment]
I'm not confident if it can be generalized. I know it will help us in our binding system, where the bulk of the time we won't have more than 3 subscribers to the same property. We will likely have to custom implement it because of the need for calling the subscribers. I don't want to implement an iterator for a custom collection, because that would be slow. So, I think we may be left having to copy paste this pattern into a few places. Not sure just yet.

**Comment by wardbell** [comment]
Rob - what is your opinion about double subscriptions w/ same callback? It can be costly to check for previous subscription w/ that callback I suppose

**Comment by EisenbergEffect** [comment]
That I'm not sure about. I'm worried that checking it in our binding system would kill some of the perf benefits we hope to obtain. In our system, I don't imagine this would happen under normal circumstances. I need to understand a bit more about why this is happening in the Breeze case.

**Comment by wardbell** [comment]
There is nothing about breeze that demands this AFAIK. I believe the check for previous callback registration was Jeremy's innovation and I just went with it. :-)

No question that there's a perf cost in this hot code path. Not sure that it pays off often even if it is a PITA to guard against for the developer (as discussed earlier); too bad for him/her.

Jeremy - was there a reason you checked for duplicates in the array before adding a callback?

**Comment by jdanyow** [comment]
@wardbell - right totally my change, now i'm back-peddling on it.. was making it work more like .net subscriptions where subscribing twice didn't mean two handler invocations.

@EisenbergEffect question about this statement:

> Ultimately, the bulk of all binding operations should never create or touch an array, nor create a closure.

does this mean we'll move away from returning an unsubscribe function from the subscribe method in favor of returning a subscription token (maybe the index into the callbacks array) ?

**Comment by wardbell** [comment]
@jdanyow Actually, in .NET, subscribing twice with the same callback fn DOES mean two invocations. I'll eat my hat if I'm wrong about that.

No way you can return an index. The implementation should be free to relocate the callback internally no matter how it is stored.

I like returning the unsubscribe fn. What's wrong with that?

**Comment by wardbell** [comment]
Confirmed in .NET

```
private int count = 0;
private event System.EventHandler _show;

// Add event handlers to Show event.
_show += HiThere;
_show += HiThere;
_show += HiThere;

 // Invoke the event.
 _show(this, new System.EventArgs());

void HiThere(object sender, System.EventArgs args) {
     if (count > 0) {
       throw new System.Exception("called twice"); // and it does
    }
    System.Console.WriteLine("Hi there " + count++);
}
```

**Comment by jdanyow** [comment]
looks like I'll be doing the hat eating...

re: returning the unsubscribe fn- it's a closure, was asking if that was one we were going to try and eliminate

or does bind not count as a closure?

**Comment by wardbell** [comment]
Ah.  I suppose it can return an "unsubscribe token" consisting of the {propertyName, callback}. That's probably better.

I can't remember what lead us to return a fn. Is that what Aurelia expected? Rather than have Aurelia call the `propertyObserver.unsubscribe`?

**Comment by EisenbergEffect** [comment]
@jdanyow Yes, it means we will not be returning an unsubscribe function. The creates lots of closures during the process of binding a view is something we need to get rid of.

We will probably extend the interface wit an `unsubscribe` method that you would pass the original subscriber into to unsubscribe. It's a bit more tedious, but this is low level stuff, so I think it's ok. Another key element to this is using "callables". So, rather than subscribing with a callback (which is another closure) you would pass an object instance that has a `call` method. It so happens that functions have `call` so you can interchange them, if you allow passing an optional `context` as part of the subscription. So, our binding objects would actually implement `call` and pass themselves in rather than creating additional closures.

**Comment by jdanyow** [comment]
Ah like the microtaskqueue- I was wondering why the api was like that.  Learning so much from you guys!!

**Comment by wardbell** [comment]
Is a subscription callback closure all that bad? There's a good chance it is unavoidable; what the heck is that callback going to do anyway if it doesn't close on something?

School me.

**Comment by EisenbergEffect** [comment]
@wardbell This is very specific to our case. But, we already have a binding instance that captures all the data needed in its properties. We would pass that instance directly as the subscriber. Right now, we create a function to subscribe, which creates an unnecessary closure.

In the case of binding, right now, there are two closures needed for every one-way binding. One for the subscription, plus the one returned to unsubsribe with. If you want two-way binding, then that is four closures. However, we already have all the information in the binding object that is doing the subscribing, so we could implement the callable pattern in our observation system, then add a `call` method to our binding object and pass the existing instance. All we need is a simple context object to differentiate between which callback is being called. This can be a simple constant string value shared across all instances and used in an if or switch/case branch inside the `call` method.

**Comment by wardbell** [comment]
I was already on-board with killing the unsubscribe closure; return a token for sure. I was just wondering how you'd get rid of the subscribe callback closure. Still not following that completely but I'm happy to sit back and see it play out.  Thanks for the info!

**Comment by jdanyow** [comment]
closing- the aurelia benchmarking work resulted in a no-array, no-closure model to handling subscribers that was reused in the aurelia-breeze plugin.

**Comment by EisenbergEffect** [comment]
Woohoo! Bad to the bone! You are killing it man.

**Comment by wardbell** [comment]
Sweet!
