### ISSUE TITLE
Queries don't return any results in IE9

### ISSUE THREAD

**Issue by flymason** [jdanyow/aurelia-breeze#12]
When running in IE9, the results part of my query comes back as an empty array. This causes a promise rejection when the promise tries to resolve an undefined entity. The network response shows that all the results are there. The response is exactly the same as other browsers where the app works.

The same app works fine in IE11 and Chrome.

**Comment by wardbell** [comment]
IE9 is not ES5 compliant. Defined Properties in particular don't work and can't be shimmed. I rather doubt you can run a breeze/au app on IE9. That tech combo is really for modern browsers

**Comment by wardbell** [comment]
Oops.  It looks like IE9 does support [DefinedProperties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) and I was remembering that [IE8 does not](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Internet_Explorer_8_specific_notes).

So I don't know the answer to your question.

**Comment by jdanyow** [comment]
@flymason do we still have work to do here or have any of the aurelia updates or aurelia-breeze updates solved this?

**Comment by flymason** [comment]
This has been fixed. We've haven't had any recent problems using Aurelia-Breeze with IE9.
