### ISSUE TITLE
Error messages need to be configurable

### ISSUE THREAD

**Issue by gregoryagu** [jdanyow/aurelia-breeze#16]
When I put the Required attribute on a Entity Model, an appropriate error message is displayed.

```
[Required]
LastName string {get;set;}
```

For example, on the LastName field, I get a `LastName is required` message.

However, what would be even better is if the message was taken from the Required attribute:

```
[Required(ErrorMessage = "Last Name is required.")]
public string LastName { get; set; }
```

For a production app, these details are important such as a user friendly field name and a period at the end.

However, I don't think breeze actually supports this.  The message does not get included in the metadata.  I know there was discussion about this in the past on the breeze site, as I tried to resolve this once before and gave up on it and stopped using annotations and instead use Aurelia-validation so it is all configured on the client.  But perhaps we could get Ward to consider adding this in to breeze.

But the point is, I can't use breeze-validation.bind without some way of being able to configure the error messages, either on the client or the server.

I would love to use just breeze-validation, and not use Aurelia-validation if that is possible.

**Comment by jdanyow** [comment]
There's a few approaches breeze supports (there may be more, but these are the ones I'm familiar with):
1. Customize the `displayName` of the property.  By default it's the property name.  You can set the display name to something more user friendly [like this](http://stackoverflow.com/a/16740028/725866).  You could even write a routine to apply display names across all entity types and properties in the metadata store using a convention or manually maintained property-name to display-name mapping.
2. Customize the error message template.  Take a look at the bottom of [this page](http://breeze.github.io/doc-js/validation.html#customize-the-message-templates) for more details.
3. On the server, extend the standard breeze metadata with metadata pulled from your server-side entity's property attributes.  Then on the client, apply the extended metadata as needed.  [Here is the code](http://stackoverflow.com/a/26575081/725866) for this technique.  This is an approach I've used quite a bit.

I think you could quickly achieve the result you're looking for using a combination of 1 & 2 (user-friendly field name and period at end of sentence).  If you're using `[Display]` attributes on the server you might consider using a combination of 2 & 3 to automate the process a bit more.

**Comment by gregoryagu** [comment]
That is really great info Jeremy!
