### ISSUE TITLE
if.bind conflict ?

### ISSUE THREAD

**Issue by JimmiV** [jdanyow/aurelia-breeze#18]
`<div class="form-horizontal" breeze-validation.bind="newItem" show.bind="!readOnly">
   all is ok!</divb>`

`<div class="form-horizontal" breeze-validation.bind="newItem" if.bind="!readOnly">
   the form start validated!</div>`

**Comment by jdanyow** [comment]
@JimmiV - I'm not able to reproduce this in the latest build- are you still hitting this issue?

**Comment by JimmiV** [comment]
Nope ... all seems ok now. TY.

**Comment by jdanyow** [comment]
:dancers:
