### ISSUE TITLE
Setting default Header does not seem to work

### ISSUE THREAD

**Issue by gregoryagu** [jdanyow/aurelia-breeze#19]
I am trying to set a custom header (an Auth Header) but I don't see the header being passed to the server:

```
var ajaxAdapter: any = breeze.config.getAdapterInstance('ajax');
ajaxAdapter.defaultSettings = { headers: { "X-Test": "123" } };
```

Have also tried:

```
var ajaxAdapter: any = breeze.config.getAdapterInstance('ajax', 'aurelia');
ajaxAdapter.defaultSettings = { headers: { "X-Test": "123" } };
```

Any idea what is going on?

**Comment by gregoryagu** [comment]
I was able to get this to work:

```
ajaxAdapter.defaultHeaders = { "Test": "123" };
```

**Comment by plwalters** [comment]
@gregoryagu is this a bug with this lib or breeze or not a bug at all?  It's still open so trying to understand.

**Comment by shunty-gh** [comment]
I spotted this a while ago but thought it was just my misunderstanding. What I did instead was to add a request interceptor and set the header in there. I think this was happening the same in my Angular version of the app so it seems likely it's a Breeze thing.

```
ajaxAdapter.requestInterceptor = function(requestInfo) {
    ...
    requestInfo.config.headers['X-Test'] = '1 2 3';
    ...
}
```

**Comment by gregoryagu** [comment]
@PWKad, I am not really sure to be honest.  I was thinking maybe something in the custom Aurelia ajax adapter is not quite right.  However, I got it working, so it's really not an issue.  If I can nail down anything more, I will post back here. Will close in the meantime.

**Comment by gregoryagu** [comment]
Ok, I know what the issue is:

According to the breeze docs, the constructor should have this:

```
var ctor = function () {
    this.name = 'jQuery';
    this.defaultSettings = { };     
    this.requestInterceptor = null;
};
```

Instead, the Aurelia-breeze ajax adapter has this:

```
constructor() {
    this.name = 'aurelia';
    this.defaultHeaders;
    this.requestInterceptor = null;
  }
```

In other words, it should use `defaultSettings` instead of `defaultHeaders`

**Comment by dotnetrules** [comment]
Awesome catch @gregoryagu , well done!!

**Comment by jdanyow** [comment]
The `requestInterceptor` method @shunty-gh mentioned is the best way to do this.  

The `defaultHeaders` property appears to be specific to `aurelia-breeze`'s ajax adapter implementation- it doesn't appear in the breeze's built-in jQuery based or ng-$http based ajax adapter implementations.

I'm not sure where/how I came up with the `defaultHeaders` property.  It should probably be removed to be consistent with the built-in ajax adapters.

What do you guys think?

**Comment by jdanyow** [comment]
oh- ha I didn't see @gregoryagu's last comment- that makes sense.  Confirms defaultHeaders doesn't belong.  Will get this fixed.  Thanks everyone!

**Comment by gregoryagu** [comment]
Awesome!
