### ISSUE TITLE
Does ajax-adapter accidentally overwrite headers in config?

### ISSUE THREAD

**Issue by wardbell** [jdanyow/aurelia-breeze#2]
[This line](https://github.com/jdanyow/aurelia-breeze/blob/master/src/ajax-adapter.js#L34) concerns me:

```
requestInfo.config.headers = clone(this.defaultHeaders || {});
```

That will ***_replace**_ rather than _extend_ any headers that happen to be specified in the `config` from the caller. Now I admit that there will be no such headers when the caller is the breeze `EntityManager` ... at least as of today. But that could change and maybe someone else wants to use this adapter for some reason.

That's why we play it safe in other ajax adapter implementations ... like this:

```
var core = breeze.core;
var headers = core.extend({}, this.defaultSettings.headers); // copy default headers 1st
requestInfo.config.headers = core.extend(headers, requestInfo.config.headers);
```

**Comment by jdanyow** [comment]
Good catch- will fix.
