### ISSUE TITLE
Entity query withParameters error

### ISSUE THREAD

**Issue by darianferrer** [jdanyow/aurelia-breeze#20]
I'm trying to execute a query with parameters, but the generated url is wrong:

http://localhost:16746/api/v1/CountryItem?$orderby=Id&$top=10&$inlinecount=allpages<strong>?q=Sa</strong>

<pre><code>
        let manager = new breeze.EntityManager('/api/v1');

        var query = breeze.EntityQuery
            .from('CountryItem')
            .withParameters({
                q: 'Sa'
            })
            .orderBy('id')
            .skip(0)
            .take(10)
            .inlineCount();

        manager.executeQuery(query.using(breeze.FetchStrategy.FromServer), data => {
            return data;
        });
</code></pre>

Is this a bug or I'm doing something wrong?

**Comment by mPisano** [comment]
Do you have the HTML error code?

Does your controller have an 
IQuerable<type> CountryItem(string q){}
or just the main
IQuerable<type> CountryItem(){}

if so - call
 EntityQuery.from('CountryItem').where('???', 'eq', 'sa').orderBy('id').skip(0).take(10).inlineCount();

If not then  Wait for Jeremy.... He's the master!

HTH
Mike

**Comment by darianferrer** [comment]
It's a Bad Request error (400), if you see the url, there are two '?' characters, server says "'allpages?q=Sa' is not a valid value for $inlinecount."

I'm not sure if it's a bug of aurelia-breeze or aurelia-http-client, so I guess I'll wait for Jeremy, thanks Myke.

**Comment by shunty-gh** [comment]
A similar thing happens when you combine a .withParameters and a .where clause. The query builder seems not to take into account the fact that a query string has already been started and so adds a second ? to the string. I got a bit lost tracing through after that though.

**Comment by mPisano** [comment]
@darianferrer - Ahh, didn't see the double question marks - might be a bug. 
I'm using Jeremys code but I am only calling withparameters for single entities, not with odata filters like your attempting.

For me, when i'm returning paged lists, i'm adding the filter on the backend for security after the user has logged into the controller, which may be a possible solution and workaround. (ie)

```
    public class MyContext : DbContext
    {
        public DbSet<CountryItem> countryitem{ get; set; }
    }

 [HttpGet]
        public IQueryable<CountryItem> CountryItem()
        {
           string name = Thread.CurrentPrincipal.Identity.Name;  //sa
           IQueryable<CountryItem> q = countryitem.Where(x => x.user == name); //client will add Skip/Take
            return q;
        }
 [HttpGet]
        public IQueryable<CountryItem> CountryItem(int id)
        {
           string name = Thread.CurrentPrincipal.Identity.Name;  //sa
           IQueryable<CountryItem> q = countryitem.Where(x =>  x.id == id && x.user == name); //make sure row belongs to user
            return q;
        }
```

HTH,
Mike

**Comment by darianferrer** [comment]
@mPisano - I found a workaround: instead of using .withParameters(), I ended using .where(), it works well:

http://localhost:16746/api/v1/CountryItem?$filter=startswith(Name%2C%27Sa%27)%20eq%20true&$orderby=Id&$top=10&$inlinecount=allpages

I think the problem might be withParameters() not knowing there is already a query string generated, as said by @shunty-gh 

Darian
