### ISSUE TITLE
The plugin won't load.

### ISSUE THREAD

**Issue by erenard** [jdanyow/aurelia-breeze#22]
Hi, here is the stacktrace I get when I add aurelia-breeze to my app : 

DEBUG [aurelia] Loading plugin aurelia-breeze.
## es6.promise.js:139 Unhandled promise rejection Error: Error invoking TaskQueue. Check the inner error for details.

inner error: TypeError: _aureliaPal.DOM.createMutationObserver is not a function
    at makeRequestFlushFromMutationObserver (http://localhost:9000/jspm_packages/npm/aurelia-task-queue@1.0.0-beta.1/aurelia-task-queue.js:13:36)
    at new TaskQueue (http://localhost:9000/jspm_packages/npm/aurelia-task-queue@1.0.0-beta.1/aurelia-task-queue.js:59:41)

Id there a precise version of aurelia-pal, having a createMutationObserver ?

Aurelia is the configured this way : 
    aurelia.use
        .standardConfiguration()
        .developmentLogging()
        .plugin("aurelia-breeze")
        .feature("resources");

I have added the following dependencies : 
      "aurelia-binding": "npm:aurelia-binding@^1.0.0-beta.1.0.1",
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.18.0",
      "aurelia-breeze": "npm:aurelia-breeze@^0.13.1",
      "aurelia-dependency-injection": "npm:aurelia-dependency-injection@^1.0.0-beta.1",
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@^1.0.0-beta.1",
      "aurelia-framework": "github:aurelia/framework@^0.17.0",
      "aurelia-http-client": "npm:aurelia-http-client@^1.0.0-beta.1",
      "aurelia-logging-console": "github:aurelia/logging-console@^0.8.0",
      "aurelia-router": "github:aurelia/router@^0.13.0",
      "bootstrap": "github:twbs/bootstrap@^3.3.5",
      "breeze": "npm:breeze-client@^1.5.5",
      "font-awesome": "npm:font-awesome@^4.4.0",
      "jonmiles/bootstrap-treeview": "github:jonmiles/bootstrap-treeview@^1.2.0",
      "jquery": "github:components/jquery@^2.1.4"

Thank you

**Comment by jdanyow** [comment]
execute `jspm inspect --forks`... do you have any forks?

# Edit

I see from your deps that you do have some forks... 
please execute `jspm install _____` for every dependency in the jspm section of your package.json... eg [all these](https://github.com/aurelia/skeleton-navigation/blob/1.0.0-beta.1.0.1/package.json#L61-L75).

**Comment by erenard** [comment]
Thank you very much, you solved my problem.

I had to `jspm install ____` for every aurelia related dependency, and the fork disappeared.

You might want to change the arelia-breeze version to 1.0.0-beta.1 eventually.

**Comment by jdanyow** [comment]
nice!
