### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by Vaccano** [jdanyow/aurelia-breeze#23]
Any chance for a simple typescript definition file for this?

I am trying to use it in a visual studio project that compiles with typescript. When I do this:

```
 import {ErrorRenderer} from 'aurelia-breeze';
```

I get an error of:

```
 Cannot find module 'aureila-breeze'
```

I can import other framework stuff:

```
 import {Container, autoinject} from 'aurelia-framework'
```

This works fine (and seems like a similar example to 'aurelia-breeze'.  

However if I exclude aurelia-framework.d.ts from my project then it gives a similar  error:

```
 Cannot find module 'aurelia-framework'
```

And when I put aurelia-framework.d.ts back in, that error goes away.

So this leads me to believe that I need an aurelia-breeze.d.ts.  

I would make my own, but the setup with index.js as the core of the exports for the project is confusing me.  (I am new to typescript and javascript so I may be in over my head a bit.)

**Comment by jdanyow** [comment]
Will get this into the build, in the meantime, here's the d.ts:

``` typescript
declare module 'aurelia-breeze' {
  import {ValidationError, DataProperty} from 'breeze';

  export interface ErrorRenderer {
    render(rootElement: Element, error: ValidationError, property: DataProperty): void;
    unrender(rootElement: Element, error: ValidationError, property: DataProperty): void;
  }
}
```

**Comment by jdanyow** [comment]
The validation piece is in the process of being moved to a separate repo and integrated with aurelia-validation.  Since there will be no public API in aurelia-breeze I'm closing this issue.
