### ISSUE TITLE
“Q js is undefined.” while trying to resolve promise from aurelia-breeze in test method(karma+jasmine)

### ISSUE THREAD

**Issue by jithinoj** [jdanyow/aurelia-breeze#24]
I am consistently getting an error while trying to resolve a promise from` aurelia-breeze `in a test method for an `aurelia(typescript + breeze)` application.

Testing framework used is `karma+jasmine`.
Version of the `aurelia-breeze` package is `1.0.0`

Aurelia breeze makes use of es promise resolver instead of `Q.js`, but the test method is searching for `Q.js` to resolve the promise returned from breeze.

I have tried to add the `Q` library to the window object from the spec file. But the `breeze.debug.js` is trying to access the `Q j`s from the window object before it is set in the spec file.
this didn't resolve the issue.

Please help me to solve this issue.

**Comment by jithinoj** [comment]
I was able to fix the issue bu

```
import {configure as configureAureliaBreeze} from 'aurelia-breeze/index';
import {Container} from 'aurelia-framework';
```

```
const container = new Container();
configureAureliaBreeze({ container, globalResources: () => {} });
```

// ... tests ...

**Comment by jdanyow** [comment]
http://stackoverflow.com/a/35582571/725866
