### ISSUE TITLE
Error with webpack skeleton

### ISSUE THREAD

**Issue by darianferrer** [jdanyow/aurelia-breeze#25]
Hi,
I'm trying to setup this plugin with the webpack skeleton app, it does well when webpack creates the bundles, but then when I run the app throws an error:

Unhandled rejection Error: Cannot find module './aurelia-breeze/validation/breeze-validation'

I think the problem is when it executes this line: `frameworkConfig.globalResources('./validation/breeze-validation');`

Maybe I should register breeze-validation as a plugin in my aurelia config?

**Comment by istrau2** [comment]
The fix to this is to add "aurelia-breeze" to webpack's includSubModules array. Still after this there is another issue that pops up in which breeze complains that "Q is not defined". 

It would be really nice if this library was made to work with webpack as I think more and more people are moving that way from jspm (I did) just because of the headache that comes along with jspm/SystemJS.

**Comment by jdanyow** [comment]
just published a new build, let me know if this resolves the issue.

**Comment by darianferrer** [comment]
Hi @jdanyow still getting the 'Q is not defined' error with latest release, I'm uploading my webpack config file because I'm not a webpack expert, maybe I'm missing something there.

[webpack.config.txt](https://github.com/jdanyow/aurelia-breeze/files/239113/webpack.config.txt)

**Comment by jdanyow** [comment]
I wonder if webpack is loading two instances of breeze?  `aurelia-breeze` imports `breeze` and call's `setQ`.

https://github.com/jdanyow/aurelia-breeze/blob/master/src/index.js#L13

**Comment by flieks** [comment]
it's not only webpack
I'm bundling with jspm and then at runtime i also get 
`global.window is undefined.` 
which is in 
`var Q = __requireLibCore("Q");`
i'm using auerlia-breeze@1.0.0

**Comment by flieks** [comment]
i switched to webpack and that worked for 
"aurelia-breeze": "^1.2.0"
and
"breeze": "^1.2.2"
