### ISSUE TITLE
Support for the webpack skeleton

### ISSUE THREAD

**Issue by istrau3** [jdanyow/aurelia-breeze#26]
I have an app built using the webpack skeleton. I tried:

``` javascript
npm install aurelia-breeze
```

Everything seems to have come down except that there is no module 'breeze' rather a module 'breeze-client'

When I try to bundle with webpack I get a bunch of errors of this type:

``` javascript
Module not found: Error: Cannot resolve module 'breeze'
```

from the aurelia-breeze source.

**Comment by darianferrer** [comment]
Hi @istrau3 you need to change webpack configuration to resolve that:

`resolve: {
      alias: {
          'breeze': 'breeze-client/build/breeze.debug'
      }
  },`

After that, webpack no longer throws error, but when running the application this issue happens:
https://github.com/jdanyow/aurelia-breeze/issues/25

**Comment by istrau3** [comment]
@jdanyow Just an update. The issue with webpack has boiled down to an error thrown by breeze where it cannot find a 'Q' library (which aurelia-breeze sets in its configure function).

I looked into this more. It seems that the instance of breeze that is being returned when breeze is imported from some code:

``` javascript
import breeze from 'breeze';
```

is not the same instance that is configured by aurelia-breeze (which is why breeze can't find Q). In the configure function of aurelia-breeze I tried the following:

``` javascript
window.breeze = breeze;
```

and then in my code, instead of importing from breeze I just used breeze from the window. This fixed this issue. I realize that this is not an elegant fix (kind of  a hack). I just wanted to post an update because I really need this to work (holding back my whole project at this point - I am trying to convert an angular/breeze app to an aurelia/breeze app).

Thanks.

**Comment by jdanyow** [comment]
just published a new build, let me know if this resolves the issue.

**Comment by istrau3** [comment]
Sorry I have been slow to respond, will try and test within the next week or so (decided to pass on breeze for the current project)

**Comment by jdanyow** [comment]
ok- I will close this one and continue tracking this here: https://github.com/jdanyow/aurelia-breeze/issues/25
