### ISSUE TITLE
ajax-adapter for aurelia-fetch-client - the Aurelia project's official ajax library

### ISSUE THREAD

**Issue by rockResolve** [jdanyow/aurelia-breeze#27]
aurelia-fetch-client (replacing aurelia-http-client) is now the Aurelia project's official ajax library (e.g. in skeleton projects) ref: https://github.com/aurelia/fetch-client/issues/7

Can we please have an ajax adapter that uses aurelia-fetch-client

**Comment by alfkonee** [comment]
@jdanyow Any Update on this

**Comment by alfkonee** [comment]
@rockResolve here's an update  #28 let's discuss on the changes made and get @jdanyow to merge it if all looks good

**Comment by mijohen** [comment]
Looks good to me. @jdanyow can you review and merge this please.

**Comment by jdanyow** [comment]
@hendo-michael I took a look- definitely appreciate @alfkonee's pull request.  Just need the tests updated and it can be merged.

**Comment by rockResolve** [comment]
Found bug & fix with defaults not passed though. Notes in PR

**Comment by rockResolve** [comment]
Breeze withParameters does not work.
The root cause is fetch (& therefore aurelia-fetch-client) do not support params
https://github.com/github/fetch/issues/167

The workaround is to put the params in the query string. Working on a fix.

**Comment by rockResolve** [comment]
So the fix is quite simple. I copied some code from Breeze.AjaxAngularAdapter (which has to solve a similar problem) into my code and it works.

I put the fix in this aurelia-breeze. But maybe the fix should be in aurelia-fetch-client.
I preferred aurelia-breeze because aurelia-fetch-client should only have fetch processing (or at the most a warning). What is your preference?

**Comment by jdanyow** [comment]
Sounds good to me- please create a PR and I'll review more thoroughly

**Comment by rockResolve** [comment]
PR #31 added with the above fixes added. Also updated tests.

**Comment by jdanyow** [comment]
v2.0.1 using aurelia-fetch-client has been published.  Thanks @rockResolve!
