### ISSUE TITLE
Can't install aurelia-breeze -  Repo npm:breeze@breeze-client not found!

### ISSUE THREAD

**Issue by ericwscott** [jdanyow/aurelia-breeze#29]
jspm-install aurelia-breeze results in:

err  Error: Repo npm:breeze@breeze-client not found!

I have tried jspm clean, jspm cc, and jspm install -f.

I get the same error with both skeleton-typescript and skeleton-es2016.

**Comment by jdanyow** [comment]
not sure what's going on here.  will check with the jspm team

**Comment by flieks** [comment]
I'm having this issue too

```
jspm install aurelia-breeze
Updating registry cache...
     Looking up npm:aurelia-breeze
     Downloading npm:aurelia-breeze@1.1.5

warn Error on processPackageConfig
     Package.json dependency breeze set to npm:breeze-client, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.
```

**Comment by flieks** [comment]
i installed back to 1.0.0 which works

**Comment by tokyo2002** [comment]
Is the fix as simple as changing the dependencies in the package.json file? 

From This....

```
"dependencies": {
      "aurelia-binding": "^1.0.0-beta.1.3.2",
      "aurelia-http-client": "^1.0.0-beta.1.2.0",
      "aurelia-pal": "^1.0.0-beta.1.2.0",
      "aurelia-templating": "^1.0.0-beta.1.2.2",
      "breeze": "npm:breeze-client"
    },
```

To This...  Adding the SEMVER back into the breeze-client line.

```
"dependencies": {
      "aurelia-binding": "^1.0.0-beta.1.3.2",
      "aurelia-http-client": "^1.0.0-beta.1.2.0",
      "aurelia-pal": "^1.0.0-beta.1.2.0",
      "aurelia-templating": "^1.0.0-beta.1.2.2",
      "breeze": "npm:breeze-client@^1.5.6"
    },
```

I am a rookie at Github, so not sure how to do a pull request.  Sorry.
Kris...

**Comment by flieks** [comment]
you can do
`jspm install aurelia-breeze=github:jdanyow/aurelia-breeze@1.0.0`
Problem is you will have forks as this version doesn't use the latest version of aurelia

**Comment by jdanyow** [comment]
give it a try now- I tried @tokyo2002's changes but ultimately had to get rid of the `"breeze": "npm:breeze-client@^1.5.6"` in favor of `"breeze-client": "^1.5.6"`.  This is probably a breaking change for those of you who installed breeze using `jspm install breeze` instead of `jspm install npm:breeze-client`.

**Comment by tokyo2002** [comment]
Just to clarify... Should breeze be install using `jspm install npm:breeze-client` ?
If so, it may be a good idea to update the Readme.md.

**Comment by ericwscott** [comment]
Works for me now.  Thanks!

**Comment by jdanyow** [comment]
:dancers:

**Comment by cberkley** [comment]
on May 16 you guys tokyo2002 asked "Just to clarify... Should breeze be install using jspm install npm:breeze-client ? If so, it may be a good idea to update the Readme.md."

Nobody clarified and the readme.md never changed.  Any word on that?
