### ISSUE TITLE
Why does ajax-adapter have static setHttpClientFactory function?

### ISSUE THREAD

**Issue by wardbell** [jdanyow/aurelia-breeze#3]
The adapter definition has this static method (`setHttpClientFactor`) for defining the method that will determine the runtime instance of the `httpClient` used by the adapter.

I'm personally leery of statics, especially when there is no default implementation. I don't see the need in this case. IMO, it should be an adapter instance method such as;

```
setHttpClient(client) {
    this.client = client;
}
```

Configuration now looks like this:

```
var adapter = breeze.config.initializeAdapterInstance('ajax', 'aurelia', true);
adapter.setHttpClient(aurelia.container.get(HttpClient));
```

That's the way it's done with the Angular ajax adapter. It seems clearer to me and slightly easier to test. And it's one fewer method to export.

Thoughts?

**Comment by jdanyow** [comment]
I like that better too.  So there's no need for me to worry about a second/third/... instance of the adapter coming into play right?  I wasn't sure about that.

**Comment by wardbell** [comment]
Breeze treats it as a service in general. You can create your own instances for special purposes but you'd go out of your way to do that.
