### ISSUE TITLE
Issue when building with Aurelia-CLI

### ISSUE THREAD

**Issue by dwarry** [jdanyow/aurelia-breeze#35]
Not sure if this is an issue here, or with aurelia-bundler...

I've tried creating a new project using the new release version of the cli tool (Typescript, default settings for everything else) and then adding aurelia-breeze (adding that, aurelia-fetch-client and breeze-client to the dependencies in aurelia_project/aurelia.json). When I do `au build` it looks like it's deriving the wrong filename for breeze - which should be `breeze.min.js`

```
Tracing aurelia-binding...
Tracing aurelia-bootstrapper...
Tracing aurelia-breeze...
error D:\dev\AuTest\BreezeTest\node_modules\breeze-client\breeze.js
Tracing aurelia-event-aggregator...
Tracing aurelia-dependency-injection...
Tracing aurelia-framework...
Tracing aurelia-history...
```

**Comment by dwarry** [comment]
Finally got to the bottom of this - there's a problem with Breeze when using AMD - the adapters etc. require the main module with the name "breeze" rather than "breeze-client".

I'll go and raise an issue with them...

**Comment by dotnetrules** [comment]
Hi @dwarry , I have the same issue I think. Did you ever find a resolution or workaround?
thanks

**Comment by dwarry** [comment]
Yeah, [Breeze fixed it a while ago](https://github.com/Breeze/breeze.js/issues/161) and it's been working for me since then, though I've been using JSPM rather than Aurelia-CLI recently.
