### ISSUE TITLE
BreezePropertyObserver sets entity propertyChangedEventArgs propertyName

### ISSUE THREAD

**Issue by rockResolve** [jdanyow/aurelia-breeze#36]
Symptom: other subsequent breeze entity PropertyChanged subscriptions get propertyChangedEventArgs with a random propertyName for an entity-wide change when it should be blank

Cause: aurelia-breeze subscribes to the Breeze propertyChanged event. If it is an entity event, during its processing the handleEvent method is setting the propertyName. When it exits it leaves a random propertyName in the propertyChangedEventArgs "change" object parameter.

e.g. mergeEntity after manager.saveChanges() raises PropertyChanged event on an entity with entityState.isUnchanged. Subscriptions after aurelia-breeze see these events with a random propertyName.

Use Case: I need to know of any propertyChange, and as I sometimes start with an added entity I cant use entityState changes. As I want any property change I dont want to subscribe to every properties observer.

**Comment by jdanyow** [comment]
need to set `change.propertyName` back to null before exiting here:
https://github.com/jdanyow/aurelia-breeze/blob/master/src/property-observation.js#L44

**Comment by rockResolve** [comment]
Thanks. Wasn't sure if you'd want to create new propertyChange objects to avoid async processes getting mutated objects, but seemed an obscure use case.

**Comment by jdanyow** [comment]
Shouldn't be an issue given the single threaded nature of the runtime. Definitely can revisit if it comes up.
