### ISSUE TITLE
Why does ajax-adapter export `HttpResponse`?

### ISSUE THREAD

**Issue by wardbell** [jdanyow/aurelia-breeze#4]
Who needs it? It's really an object whose definition is internal to breeze itself. It's really a "private" contract between an ajax adapter and the Breeze `EntityManager`.

You don't use it elsewhere in the repo and know consumer of Breeze should know it exists.

I recommend minimizing exports as much as possible.

> If you combine this with my other recommendations, you'll have a module that exports an empty object. Nothing wrong with that IMO. It's a module with a side-effect; it defines an adapter and registers it with Breeze.

**Comment by jdanyow** [comment]
Same reasoning as the other issue- enables unit testing/reuse.  Can you elaborate on why exports should be minimized?  I'm definitely open to changing this.

**Comment by wardbell** [comment]
If testing the adapter in isolation, you get the httpResponse as part of the value in the callback. Whether the object is a published class or just a JS object has no effect on the adapter's testability (although it would affect intellisense if we had that)

The main point, however, is that it isn't your class. It's Breeze's class. It's  part of a semi private contract in breeze adapter land.

The adapter's public API should only contain public members (ideally). Because JS doesn't support a diverse member accessibility model, we are often obliged to make public what would otherwise be private. We try to indicate that with conventions like '_' in member names as in `_semiPrivate`. We try to minimize such junk when we can. Here you have no need of it.

Personally, I'm always striving for the minimal interface. It reduces my commitments, the testing service, the learning surface.

I can always open up later if I have too but it's very hard to subtract from a published interface.

Such is my thought process.

**Comment by wardbell** [comment]
"testing surface", not "service"

**Comment by jdanyow** [comment]
good points- thanks for elaborating on this, I'll do as you've recommended.
