### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by TSDSATHISH** [jdanyow/aurelia-breeze#40]
I am using this Aurelia Breeze plugin.

My use case is that I have to pass Uer Name/Password to the REST API that I am consuming for Authentication.

Could you please show a direction on how I can achieve the authentication.  Googled a lot, but left clueless

**Comment by TSDSATHISH** [comment]
Any luck on this guys. Need to resolve this ASAP. Please give me a helping hand.

**Comment by jdanyow** [comment]
Please post questions like this on stackoverflow. You'll need to register an HttpClient instance in the container that has been configured with your credentials.
