### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by renan-garcia** [jdanyow/aurelia-breeze#48]
The current version of aurelia-breeze 2.2.0 does not work correctly with this example (https://plnkr.co/edit/XMmSqT?p=preview), it validates but does not render the error. Is there any fix that I can do? Any other example with a more current version? Do you have any other way to show your mistakes? thank you

Obs: the last version that I managed to make it work was 1.0.0

**Comment by thechop** [comment]
I noticed the same thing. Maybe this functionality has been removed but the documentation hasn't been updated.

Chris

**Comment by jdanyow** [comment]
form validation was removed from aurelia-breeze but you can add the `breeze-validation` custom attribute directly to your project:

https://github.com/jdanyow/aurelia-breeze/tree/ef682ff95d4fe89d22788449185715b03776d823/src/validation

**Comment by renan-garcia** [comment]
@jdanyow
Is this the best way? I tried to integrate with aurelia-validation but I had problems see:
Http://stackoverflow.com/questions/43232972/implement-aurelia-breeze-validation?noredirect=1#comment73544257_43232972
