### ISSUE TITLE
Just one breeze propertyChanged handler per bound entity?

### ISSUE THREAD

**Issue by wardbell** [jdanyow/aurelia-breeze#6]
> Caveat: everything I say here is based on my reading the code, not executing it. I could easily have misread something and I invite you to correct me.

It appears that you are adding a new subscription to each entity’s `entityAspect.propertyChanged` event for _every_ data bound property. That _works_. But will it _scale_? If we bind to 1000 entities each with 10 bound properties, that’s 10,000 event handlers.

I think we can get it down to one handler per entity. 
## Proposal

Imagine for each observed entity you have a `BreezeObjectObserver` (AKA `boo`) ... as you do now. The `boo` has a dictionary (a hash) of {propertyName, callbacks} where the callbacks are the Aurelia listeners; let's call that thing `watches`. 

For efficiency we also keep a count of the number of subscriptions in the dictionary; call this `subscriptionCount`. 

When Aurelia asks for a property observer, we get or create the new `BreezeObjectObserver`. 

Then we add a property to `boo.watches` (if necessary) and add to its array of callbacks (which will have one element the first time). we bump the `boo.subscriptionCount` by 1. We return the unsubscribe function …  as you do.

The first time we create a `boo`, we register a SINGLE breeze `propertyChanged` handler to `entityAspect.propertyChanged`.

Because breeze raises the changed event by property name, it’s trivial for that handler to find the watch for that property and get its array of callbacks: `boo.watches[propertyName]`. Pretty much the logic you have.

Unsubscribe is a matter of calling the unsubscribe function (as you do) and decrementing the `boo.propertyCount`.

> Or perhaps setting the slot in the array to `null` instead!  Jay found that it is significantly faster to stick nulls in an array rather than keep expanding and shrinking it. That repeated restructuring can force a lot of garbage collection apparently. It’s a little more work to fill with nulls and watch for nulls but he found it worthwhile. See the implementation of the Breeze `EntityGroup`.  This is a refinement to be sure and not critical to the proposal.

When the `boo.propertyCount` === 0, we know we can unsubscribe from `entityAspect.propertyChanged`.

> I think I would also discard the `boo` (`object.entityAspect.__breezeObserver__ = undefined`).
> 
> We'd have to harden the unsubscribe function against the risk that it was associated with a `boo` that no longer exists ... or is no longer valid. I don't think that's hard.
> 
> That is a refinement. You could always keep it and re-subscribe when the count === 1.

**Comment by jdanyow** [comment]
It does only subscribe once per entity- BreezePropertyObserver.subscribe call's into it's parent BreezeObjectObserver which manages the single propertychanged subscription for the entity:  https://github.com/jdanyow/aurelia-breeze/blob/master/src/property-observation.js#L28

I'll look into the other changes around optimizing unsubscribe and discarding `__breezeObserver__`.

**Comment by wardbell** [comment]
Hmm. Forgive me. You do only subscribe once per entity.

But I'm still mystified (remember that I'm reading code, not running it).

For each call to `boo.subscribe` you [set the captured `callbacks` array from the `propertyObserver`](https://github.com/jdanyow/aurelia-breeze/blob/master/src/property-observation.js#L39). That's an array of _callbacks for a single property_, right? The `boo` itself doesn't have its own callbacks array. 

Yet the [returned `unsubscribe` method](https://github.com/jdanyow/aurelia-breeze/blob/master/src/property-observation.js#L51) unsubscribes from the breeze `propertyChanged` event _whenever that single property's callback collection becomes empty_.

That means that after one property becomes completely unsubscribed, **boo won't be listening to changes for any other properties of the entity**, right !?!

I didn't see any tests that cover multiple property changes and, in particular, what happens when you unsubscribe to one property but not the others.

> That **will happen** when the same entity is bound to multiple views ... but not all of its properties are bound on all views.

Did I miss those tests?

**Comment by jdanyow** [comment]
you're right- this is definitely a bug, I'll fix this with the rest of the items and make sure there are tests for this scenario.

**Comment by jdanyow** [comment]
@wardbell missing tests added, property observation code heavily refactored.
