### ISSUE TITLE
Make unsubscribe flyweight

### ISSUE THREAD

**Issue by wardbell** [jdanyow/aurelia-breeze#8]
The [current unsubscribe method](https://github.com/jdanyow/aurelia-breeze/blob/master/src/property-observation.js#L50) returned from a subscription is kind of heavy and holds several captures.

```
return function() {      
    callbacks.splice(callbacks.indexOf(callback), 1);
    if (callbacks.length > 0)
        return;
    this.obj.entityAspect.propertyChanged.unsubscribe(this.subscription);
    this.observing = false;
}.bind(this);
```

This might matter because you'll create so many of them.

I'd rather see it be ...

```
return function() {this.unsubscribe(callback, propertyName);}.bind(this);
```

and delegate the details to `unsubscribe`.

Better still if you write:

```
callback.propertyName = propertyName;
return function() {this.unsubscribe(callback);}.bind(this);
```

**Comment by jdanyow** [comment]
The unsubscribe function is returned from the BreezeObjectObserver which maintains the single breeze entity propertychanged subscription as well as all the callbacks for all of the property subscriptions.  I don't think that distinction changes anything, you're right- it's too heavy, holds too many captures.  I'll refactor as you suggested, I think I understand what to do but I may need you to take a second look at it.

Thanks for reviewing all this stuff

**Comment by jdanyow** [comment]
@wardbell https://github.com/jdanyow/aurelia-breeze/blob/master/src/property-observation.js#L40
